name: roll-and-rake
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy>=1.23.4
  - tensorflow-probability=0.17.0
  - gym=0.21.0
  - pip
  - pip:
    - tensorflow-macos>=2.10.0
    - tensorflow-metal>=0.6.0